[package]
name = "crazyflie-link"
version = "0.2.0"
authors = ["Arnaud Taffanel <arnaud@bitcraze.io>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
crazyradio = { version = "0.1.6", features = ["shared_radio"] }
flume = "0.10"
log = "0.4"
rand = "0.8"
thiserror = "1"
url = "2.2"
hex = "0.4.3"
async_executors = { version = "0.4.1", features = ["async_std"] }
futures = "*"
futures-util = "0.3.14"

[dev-dependencies]
anyhow = "1"
byteorder = "1.2.2"
structopt = "0.3"
"async-std" = { version = "1.9", features = ["attributes"] }
